name: Semantic release 

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install 
      - name: Build app
        run: npm run build 
      - name: Install semantic release dependencies
        run: npm install --save-dev semantic-release @semantic-release/git
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release